"""
author: Stergios Mekras

email: stergios.mekras@gmail.com
"""

religious_fixed = {
    1: {
        1: {
            0: {"holiday": 0,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 1,
                "names_primary": [103],
                "names_secondary": [187]},
            2: {"holiday": 2,
                "names_primary": [631],
                "names_secondary": []},
            3: {"holiday": 3,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 4,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 5,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 6,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 7,
                "names_primary": [],
                "names_secondary": []}
        }, 2: {
            0: {"holiday": 8,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 9,
                "names_primary": [593],
                "names_secondary": []},
            2: {"holiday": 10,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 11,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 12,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 13,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 14,
                "names_primary": [],
                "names_secondary": [589]},
            7: {"holiday": 15,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 16,
                "names_primary": [],
                "names_secondary": []}
        }, 3: {
            0: {"holiday": 8,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 17,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 18,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 19,
                "names_primary": [128],
                "names_secondary": []},
            4: {"holiday": 20,
                "names_primary": [],
                "names_secondary": []}
        }, 4: {
            0: {"holiday": 21,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 22,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 23,
                "names_primary": [],
                "names_secondary": [495]},
            3: {"holiday": 24,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 25,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 26,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 27,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 28,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 29,
                "names_primary": [],
                "names_secondary": []}
        }, 5: {
            0: {"holiday": 30,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 31,
                "names_primary": [276, 288],
                "names_secondary": []},
            2: {"holiday": 32,
                "names_primary": [613],
                "names_secondary": []},
            3: {"holiday": 33,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 34,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 35,
                "names_primary": [],
                "names_secondary": []}
        }, 6: {
            0: {"holiday": 36,
                "names_primary": [281, 277, 308, 501, 527, 670],
                "names_secondary": []},
            1: {"holiday": 37,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 38,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 39,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 40,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 41,
                "names_primary": [],
                "names_secondary": []}
        }, 7: {
            0: {"holiday": 42,
                "names_primary": [323, 566],
                "names_secondary": []},
            1: {"holiday": 43,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 44,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 45,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 46,
                "names_primary": [588],
                "names_secondary": []},
            5: {"holiday": 47,
                "names_primary": [],
                "names_secondary": []}
        }, 8: {
            0: {"holiday": 48,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 49,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 50,
                "names_primary": [104],
                "names_secondary": []},
            3: {"holiday": 51,
                "names_primary": [339, 514],
                "names_secondary": []},
            4: {"holiday": 52,
                "names_primary": [6],
                "names_secondary": []},
            5: {"holiday": 53,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 54,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 55,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 56,
                "names_primary": [],
                "names_secondary": []},
            9: {"holiday": 57,
                "names_primary": [164],
                "names_secondary": []},
            10: {"holiday": 58,
                 "names_primary": [],
                 "names_secondary": []},
            11: {"holiday": 59,
                 "names_primary": [],
                 "names_secondary": []},
            12: {"holiday": 60,
                 "names_primary": [],
                 "names_secondary": []},
            13: {"holiday": 61,
                 "names_primary": [],
                 "names_secondary": []},
        }, 9: {
            0: {"holiday": 62,
                "names_primary": [],
                "names_secondary": [273]},
            1: {"holiday": 63,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 64,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 65,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 66,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 67,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 68,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 69,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 70,
                "names_primary": [],
                "names_secondary": []},
            9: {"holiday": 71,
                "names_primary": [],
                "names_secondary": []},
            10: {"holiday": 72,
                 "names_primary": [],
                 "names_secondary": []},
        }, 10: {
            0: {"holiday": 73,
                "names_primary": [],
                "names_secondary": [140]},
            1: {"holiday": 74,
                "names_primary": [162],
                "names_secondary": []},
            2: {"holiday": 75,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 76,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 77,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 78,
                "names_primary": [],
                "names_secondary": []},
        }, 11: {
            0: {"holiday": 79,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 80,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 81,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 82,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 83,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 84,
                "names_primary": [],
                "names_secondary": [267]},
            6: {"holiday": 85,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 86,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 87,
                "names_primary": [],
                "names_secondary": []},
        }, 12: {
            0: {"holiday": 88,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 89,
                "names_primary": [435, 628],
                "names_secondary": []},
            2: {"holiday": 90,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 91,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 92,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 93,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 94,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 95,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 96,
                "names_primary": [],
                "names_secondary": []},
            9: {"holiday": 97,
                "names_primary": [],
                "names_secondary": []},
            10: {"holiday": 98,
                 "names_primary": [],
                 "names_secondary": []},
            11: {"holiday": 99,
                 "names_primary": [],
                 "names_secondary": []},
            12: {"holiday": 100,
                 "names_primary": [],
                 "names_secondary": []},
            13: {"holiday": 101,
                 "names_primary": [],
                 "names_secondary": []},
        }, 13: {
            0: {"holiday": 102,
                "names_primary": [200],
                "names_secondary": []},
            1: {"holiday": 103,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 104,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 105,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 106,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 107,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 108,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 109,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 110,
                "names_primary": [],
                "names_secondary": []},
            9: {"holiday": 111,
                "names_primary": [],
                "names_secondary": []},
        }, 14: {
            0: {"holiday": 112,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 113,
                "names_primary": [482],
                "names_secondary": []},
            2: {"holiday": 114,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 115,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 116,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 117,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 118,
                "names_primary": [],
                "names_secondary": []},
        }, 15: {
            0: {"holiday": 119,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 120,
                "names_primary": [],
                "names_secondary": [585]},
            2: {"holiday": 121,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 122,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 123,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 124,
                "names_primary": [],
                "names_secondary": []},
        }, 16: {
            0: {"holiday": 125,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 126,
                "names_primary": [],
                "names_secondary": [175, 436, 531]},
            2: {"holiday": 127,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 128,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 129,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 130,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 131,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 132,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 133,
                "names_primary": [],
                "names_secondary": []},
        }, 17: {
            0: {"holiday": 134,
                "names_primary": [56],
                "names_secondary": []},
            1: {"holiday": 135,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 136,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 137,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 138,
                "names_primary": [267],
                "names_secondary": []},
            5: {"holiday": 139,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 140,
                "names_primary": [],
                "names_secondary": []},
        }, 18: {
            0: {"holiday": 141,
                "names_primary": [18, 362],
                "names_secondary": []},
            1: {"holiday": 142,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 143,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 144,
                "names_primary": [269],
                "names_secondary": []},
            4: {"holiday": 145,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 146,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 147,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 148,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 149,
                "names_primary": [],
                "names_secondary": []},
        }, 19: {
            0: {"holiday": 150,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 151,
                "names_primary": [398],
                "names_secondary": []},
            2: {"holiday": 152,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 153,
                "names_primary": [234],
                "names_secondary": []},
            4: {"holiday": 154,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 155,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 156,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 157,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 158,
                "names_primary": [],
                "names_secondary": []},
            9: {"holiday": 159,
                "names_primary": [],
                "names_secondary": []},
            10: {"holiday": 160,
                 "names_primary": [],
                 "names_secondary": []},
            11: {"holiday": 161,
                 "names_primary": [],
                 "names_secondary": []},
            12: {"holiday": 162,
                 "names_primary": [],
                 "names_secondary": []},
        }, 20: {
            0: {"holiday": 163,
                "names_primary": [216],
                "names_secondary": []},
            1: {"holiday": 164,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 165,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 166,
                "names_primary": [291],
                "names_secondary": []},
            4: {"holiday": 167,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 168,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 169,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 170,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 171,
                "names_primary": [],
                "names_secondary": []},
        }, 21: {
            0: {"holiday": 172,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 173,
                "names_primary": [406],
                "names_secondary": []},
            2: {"holiday": 174,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 175,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 176,
                "names_primary": [12, 469, 519],
                "names_secondary": []},
            5: {"holiday": 177,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 178,
                "names_primary": [210],
                "names_secondary": []},
            7: {"holiday": 179,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 180,
                "names_primary": [],
                "names_secondary": []},
            9: {"holiday": 181,
                "names_primary": [],
                "names_secondary": []},
            10: {"holiday": 182,
                 "names_primary": [],
                 "names_secondary": []},
        }, 22: {
            0: {"holiday": 183,
                "names_primary": [],
                "names_secondary": []},
            1: {"holiday": 184,
                "names_primary": [],
                "names_secondary": []},
            2: {"holiday": 185,
                "names_primary": [],
                "names_secondary": []},
            3: {"holiday": 186,
                "names_primary": [],
                "names_secondary": []},
            4: {"holiday": 187,
                "names_primary": [],
                "names_secondary": []},
            5: {"holiday": 188,
                "names_primary": [],
                "names_secondary": []},
            6: {"holiday": 189,
                "names_primary": [],
                "names_secondary": []},
            7: {"holiday": 190,
                "names_primary": [],
                "names_secondary": []},
            8: {"holiday": 191,
                "names_primary": [],
                "names_secondary": []},
        },
    },
}

secular_fixed = {
    1: {
        1: {0},
        6: {1},
        20: {2},
        21: {3},
        27: {4},
        28: {5},
        30: {6},
    },
    2: {

    }
}
